[package]
name = "custota-tool"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.1", features = ["derive"] }
cms = { version = "0.2.2", features = ["std", "builder"] }
const-oid = "0.9.5"
hex = "0.4.3"
ring = "0.17.0"
rsa = { version = "0.9.2", features = ["sha2"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
sha2 = { version = "0.10.7", features = ["std"] }
x509-cert = "0.2.4"

[dependencies.avbroot]
git = "https://github.com/chenxiaolong/avbroot"
tag = "v3.0.0"
