[versions]
android-gradle-plugin = "8.1.2"
androidx-activity = "1.8.0"
androidx-appcompat = "1.6.1"
androidx-core = "1.12.0"
androidx-fragment = "1.6.1"
androidx-preference = "1.2.1"
bouncycastle = "1.76"
jgit = "6.6.0.202305301015-r"
json = "20230618"
jsoup = "1.16.1"
jsr305 = "3.0.2"
kotlin = "1.9.0"
libsu = "5.2.1"
kotlinx-serialization = "1.5.1"
material = "1.10.0"
protobuf = "3.24.0"
protobuf-gradle-plugin = "0.9.4"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
bouncycastle-pkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-prov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
jsr305 =  { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }

# Build script
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
json = { group = "org.json", name = "json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }
