---
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
          cache: gradle

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebug -x assembleRelease

      # - name: List files in the workspace
      #   run: ls -R

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Archive artifacts
        run: |
          cp -r app/build/outputs artifacts/
          cp -r app/build/distributions artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: artifacts
