name: Update-Links

on:
  release:
    types:
      - published

jobs:
  update-links:
    runs-on: ubuntu-latest

    permissions:
        contents: write
    steps:
        - name: Check out repository
          uses: actions/checkout@v3
          with:
            submodules: true

        # https://github.com/actions/checkout/issues/290
        - name: Preserve tag annotations
          run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

        - name: Get version from git describe
          id: get_version
          run: |
            version=$(git describe | sed -E 's/v([0-9]*\.[0-9]*)-([0-9]+)-g([0-9a-f]+)/v\1.r\2.g\3/')
            echo "version=$version" >> "$GITHUB_OUTPUT"

        - name: Validate gradle wrapper checksum
          uses: gradle/wrapper-validation-action@v1

        - name: Set up Java
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
            cache: gradle

        - name: update Json Release
          run: ./gradlew updateJsonRelease

        - name: Upload release-info
          uses: actions/upload-artifact@v3
          id: upload_release_info
          with:
            name: release.json
            path: app/build/distributions/release.json

        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: update-links

        - name: Download info.json
          uses: actions/download-artifact@v3
          with:
            name: release.json
          continue-on-error: true

        - name: Get the published release's body
          id: get_release_body
          run: |
            release_body="${{ github.event.release.body }}"
            echo "::set-output name=release_body::${release_body}"

        - name: Format release body
          id: format_release_body
          run: |
            release_body="${{ steps.get_release_body.outputs.message }}"
            date="$(date +'%Y-%m-%d')"
            release_version="${{ steps.get_version.outputs.version }}"
            formatted_message="${date} ${release_version}\n${release_body}"
            echo "::set-output name=formatted_message::${formatted_message}"

        - name: Append to changelog.txt
          run: |
            formatted_message="${{ steps.format_release_body.outputs.formatted_message }}"
            if [ -f changelog.txt ]; then
              echo -e "${formatted_message}\n$(cat changelog.txt)" > changelog.txt
            else
              echo -e "${formatted_message}" > changelog.txt
            fi

        # Update the release.json file and changelog.txt, commit and push
        - name: Update release.json
          run: |
            ls -al .
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add release.json
            git add changelog.txt
            git commit -m "Update release.json ${{ github.ref }}"
            git push origin update-links
